version: "3.7"
services:
    app:
        build: .
        depends_on:
            - database
        volumes:
            - ./:/app
    database:
        environment:
            - MYSQL_DATABASE=hr
            - MYSQL_USER=hr
            - MYSQL_PASSWORD=secret-password
            - MYSQL_ROOT_PASSWORD=secret-root-password
        image: percona:5.7
        ports:
            - 3306:3306
        volumes:
            - database:/var/lib/mysql
volumes:
    database:
