parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Model/'
            - '../src/Kernel.php'

    App\Service\BonusCalculator\Calculator: '@App\Service\BonusCalculator\CompositeCalculator'

    App\Service\BonusCalculator\CompositeCalculator:
        arguments:
            $calculators:
                - '@App\Service\BonusCalculator\FixedCalculator'
                - '@App\Service\BonusCalculator\PercentageCalculator'
